version: '3.4'

services:
  stocksmart.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - DB_HOST=stocksmart.database
      - DB_PORT=5033
      - DB_NAME=stocksmart
      - DB_SA_PASSWORD=StockSmart!2024
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
